#!/usr/bin/env python3
from functions import *

# This script will update the postinstall scripts on an existing installation.

if __name__ == '__main__':
    print_error("Script not implemented yet")
