#!/usr/bin/env python3

import argparse
import os
import sys

sys.path.insert(0, "/usr/lib/eupnea")
from functions import *


# parse arguments from the cli.
def process_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--current-device-kernel", dest="current_device_kernel", action="store_true",
                        help="Use kernel from currently booted device")
    temp_args = parser.parse_args()
    if not temp_args.current_device_kernel:
        parser.add_argument("kernel_path", help="Full path to kernel image to be installed. Usage example: "
                                                "install-kernel /tmp/bzImage-new", default="Kok")
    parser.add_argument("--kernel-flags", dest="kernel_flags", default="/proc/cmdline",
                        help="Kernel flags to be used. Defaults to /proc/cmdline. Must be a full path.")
    parser.add_argument("--partition", dest="partition", default=1, help="Partition to flash kernel to. Defaults to 1")
    parser.add_argument("--device", dest="device", default="current",
                        help="Device to flash kernel to. Defaults to currently booted device.")
    parser.add_argument("--ignore-reboot", dest="ignore_reboot", action="store_true",
                        help="Force install kernel without reboot check.")
    return parser.parse_args()


if __name__ == "__main__":
    args = process_args()

    # Restart script as root
    if os.geteuid() != 0:
        sudo_args = ['sudo', sys.executable] + sys.argv + [os.environ]
        os.execlpe('sudo', *sudo_args)

    # read reboot_needed file if it exists
    if path_exists("/var/tmp/reboot_needed"):
        with open("/var/tmp/reboot_needed", "r") as f:
            reboot_needed = f.read()
        with open("/proc/sys/kernel/random/boot_id", "r") as f:
            boot_id = f.read()
        if reboot_needed == boot_id:
            print_error("System is pending a reboot. Please reboot before proceeding.")
            if not args.ignore_reboot:
                exit(65)
            else:
                print_warning("Ignoring reboot check.")

    # Exit if running from inside a chroot
    if not path_exists("/proc/mounts"):
        print_warning("Chroot detected: Skipping kernel flashing, please flash manually.")
        exit(0)

    # make tmp location
    rmdir("/tmp/kernel-install")  # delete old files
    mkdir("/tmp/kernel-install")

    if args.current_device_kernel:
        # read partitions
        partitions = bash("mount | grep ' / ' | cut -d' ' -f 1")
        partitions = partitions[:-1]  # get device name

        # save current kernel to a file
        print_status("Extracting current kernel")
        bash(f"dd if={partitions}{args.partition} of=/tmp/current_kernel")
        args.kernel_path = "/tmp/current_kernel"

    cpfile(args.kernel_path, "/tmp/kernel-install/bzImage")  # Copy image to temporary location
    cpfile(args.kernel_flags, "/tmp/kernel-install/kernel.flags")  # Write kernel flags to temporary location

    # Depthcharge automatically adds cros_secure to the kernel flags -> remove it
    with open("/tmp/kernel-install/kernel.flags", "r") as f:
        flags = f.read().replace("cros_secure", "").strip()
    with open("/tmp/kernel-install/kernel.flags", "w") as f:
        f.write(flags)

    # attempt to extract kernel if it's a raw dd
    if Path("/tmp/kernel-install/bzImage").stat().st_size > 60000000:
        print_status("Attempting to extract kernel from raw dd")
        bash("futility vbutil_kernel --get-vmlinuz /tmp/kernel-install/bzImage "
             "--vmlinuz-out /tmp/kernel-install/bzImage.raw")
    else:
        cpfile("/tmp/kernel-install/bzImage", "/tmp/kernel-install/bzImage.raw")

    print_status("Signing kernel")
    bash("futility vbutil_kernel --arch x86_64 --version 1 --keyblock /usr/share/vboot/devkeys/kernel.keyblock "
         "--signprivate /usr/share/vboot/devkeys/kernel_data_key.vbprivk --bootloader /tmp/kernel-install/kernel.flags "
         "--config /tmp/kernel-install/kernel.flags --vmlinuz /tmp/kernel-install/bzImage.raw --pack "
         "/tmp/kernel-install/bzImage.signed")

    # Read current device
    if args.device == "current":
        # get device "name"
        root_part = bash("mount | grep ' / ' | cut -d' ' -f 1")
        device = root_part[:-1]
    else:
        device = args.device
        if not device.startswith("/dev/"):
            device = f"/dev/{args.device}"
        if device[-1].isdigit():  # if device ends with a number, remove it
            device = device[:-1]

    print_status("Flashing kernel")
    bash(f"dd if=/tmp/kernel-install/bzImage.signed of={device}{args.partition}")

    # Create reboot_needed file
    with open("/proc/sys/kernel/random/boot_id", "r") as f:
        boot_id = f.read()
    with open("/var/tmp/reboot_needed", "w") as f:
        f.write(boot_id)

    rmdir("/tmp/kernel-install")  # delete files

    print_status("Kernel flashed successfully!")
