#!/usr/bin/env python3
import json
import os
import sys

sys.path.insert(0, "/usr/lib/eupnea")
from functions import *


# Expand root partition to whole drive
def expand_rootfs() -> None:
    with open("/etc/eupnea.json", "r") as file:
        eupnea_settings = json.load(file)
    if eupnea_settings["install_type"] == "image":  # only resize on image installs
        # read root partition mount
        device = bash("mount | grep ' / ' | cut -d' ' -f 1")[:-1]
        # resize partition
        bash(f'echo ", +" | sfdisk --force -N 3 {device[:-1] if device.endswith("p") else device}')
        # inform kernel of new partition
        # Only partprobe the currently booted drive, as otherwise partprobe might throw
        # Error: Can't have overlapping partitions.
        if device.startswith("/dev/sd"):  # for usb drives that start with /dev/sdX
            bash(f"partprobe {device}")
        else:
            bash(f"partprobe {device[:-1]}")
        # resize filesystem to new partition
        bash(f"resize2fs {device}3")
        # set install type to direct
        eupnea_settings["install_type"] = "expanded-image"
        with open("/etc/eupnea.json", "w") as file:
            json.dump(eupnea_settings, file)


def distro_fixes() -> None:
    with open("/etc/eupnea.json", "r") as file:
        eupnea_json = json.load(file)
    match eupnea_json["distro_name"]:
        case "ubuntu":
            if eupnea_json["de_name"] == "deepin":
                # When installing from a chroot the kernel modules are not installed
                # Therefore the modules are installed when booting for the first time
                bash("apt-get install -y ubuntudde-dde")


def set_hostname() -> None:
    # Get the board name from dmi
    with open("/sys/devices/virtual/dmi/id/product_name", "r") as dmi:
        device_board = dmi.read().lower().strip()
    # Set hostname
    bash(f"hostnamectl hostname {device_board}")


if __name__ == "__main__":
    # Elevate script to root
    if os.geteuid() != 0:
        sudo_args = ['sudo', sys.executable] + sys.argv + [os.environ]
        os.execlpe('sudo', *sudo_args)

    set_verbose(True)  # always run verbose

    while True:
        try:
            if bash("systemctl status NetworkManager.service").__contains__("active (running)"):
                sleep(5)  # wait for network service to fully start
                break
            else:
                sleep(2)
        except subprocess.CalledProcessError:
            break  # sddm is not installed

    expand_rootfs()
    set_hostname()

    # disable postinstall systemd service
    bash("systemctl disable eupnea-postinstall.service")
